#!/usr/bin/env python3
from sys import argv


def factorize():
    with open(argv[1]) as arg
    for nums in arg:
        number = int(nums)
        end = False
        for i in range(2, (number/2)+1):
            if number % i == 0:
                print("{:d}={}*{}".format(number, number//2, i))
                end = True
                break
        if not end:
            print("{:d}={}*{}".format(number, number, i))


if __name__ == "__main__":
    factorize()
